apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-kheq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0051-tenant/tkrw-pr712-0075-0051-app/devfile-sample-kheq@sha256:a102b14c89d3f99fbde15ebe83c84c174d2de4ba6a96558f769f4c8f584a5a7f
        name: my-nodejs
        resources: {}
status: {}
